apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: ecommerce-dev
  labels:
    app: proxy-client
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
        version: v1
    spec:
      containers:
      - name: proxy-client
        image: selimhorri/proxy-client-ecommerce-boot:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8900
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin-service:9411/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8900
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8900
          initialDelaySeconds: 60
          periodSeconds: 5

