version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock
      # Credenciales K8s desde el host (Windows):
      - ${USERPROFILE}/.kube:/root/.kube:ro
      - ${USERPROFILE}/.minikube:/root/.minikube:ro
    environment:
      - JAVA_OPTS=-Xmx2048m -Xms512m
      - JENKINS_OPTS=--httpPort=8080
      # Exponemos la URL del proxy para que el Jenkinsfile la use
      - KUBE_PROXY_URL=http://kubectl-proxy:8001
    networks:
      - jenkins-network
    restart: unless-stopped
    depends_on:
      kubectl-proxy:
        condition: service_healthy


  kubectl-proxy:
    image: bitnami/kubectl:latest
    container_name: kubectl-proxy
    entrypoint: ["/bin/bash"]
    command: ["/kubectl-proxy-init.sh"]
    volumes:
      - "C:/Users/Juan Diaz/.kube:/root/.kube:rw"
      - "C:/Users/Juan Diaz/.minikube:/root/.minikube:ro"
      - "./kubectl-proxy-init.sh:/kubectl-proxy-init.sh:ro"
    expose:
      - "8001"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8001/version >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped
    networks:
      - jenkins-network

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge