version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - dind-certs:/certs/client:ro
      - //d/CodeCoding/ecommerce-microservice-backend-app:/workspace:rw # Cambiar a la ruta de tu proyecto
    environment:
      - DOCKER_HOST=tcp://docker-dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins-network
    restart: unless-stopped

  docker-dind:
    image: docker:dind
    container_name: docker-dind
    privileged: true
    volumes:
      - docker-storage:/var/lib/docker
      - dind-certs:/certs/client
    networks:
      - jenkins-network
    restart: unless-stopped
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    expose:
      - "2376"

volumes:
  jenkins_home:
  docker-storage:
  dind-certs:

networks:
  jenkins-network:
    driver: bridge

