apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-stage

resources:
  - namespace.yaml
  - ../dev/service-discovery-deployment.yaml
  - ../dev/service-discovery-service.yaml
  - ../dev/cloud-config-deployment.yaml
  - ../dev/cloud-config-service.yaml
  - ../dev/zipkin-deployment.yaml
  - ../dev/zipkin-service.yaml
  - ../dev/api-gateway-deployment.yaml
  - ../dev/api-gateway-service.yaml
  - ../dev/proxy-client-deployment.yaml
  - ../dev/proxy-client-service.yaml
  - ../dev/user-service-deployment.yaml
  - ../dev/user-service-service.yaml
  - ../dev/product-service-deployment.yaml
  - ../dev/product-service-service.yaml
  - ../dev/order-service-deployment.yaml
  - ../dev/order-service-service.yaml
  - ../dev/payment-service-deployment.yaml
  - ../dev/payment-service-service.yaml
  - ../dev/shipping-service-deployment.yaml
  - ../dev/shipping-service-service.yaml
  - ../dev/favourite-service-deployment.yaml
  - ../dev/favourite-service-service.yaml

commonLabels:
  environment: staging

# Reemplazar imágenes con las del registry local
images:
  - name: selimhorri/service-discovery-ecommerce-boot
    newName: localhost:5000/service-discovery-ecommerce-boot
    newTag: latest
  - name: selimhorri/cloud-config-ecommerce-boot
    newName: localhost:5000/cloud-config-ecommerce-boot
    newTag: latest
  - name: selimhorri/api-gateway-ecommerce-boot
    newName: localhost:5000/api-gateway-ecommerce-boot
    newTag: latest
  - name: selimhorri/proxy-client-ecommerce-boot
    newName: localhost:5000/proxy-client-ecommerce-boot
    newTag: latest
  - name: selimhorri/user-service-ecommerce-boot
    newName: localhost:5000/user-service-ecommerce-boot
    newTag: latest
  - name: selimhorri/product-service-ecommerce-boot
    newName: localhost:5000/product-service-ecommerce-boot
    newTag: latest
  - name: selimhorri/favourite-service-ecommerce-boot
    newName: localhost:5000/favourite-service-ecommerce-boot
    newTag: latest
  - name: selimhorri/order-service-ecommerce-boot
    newName: localhost:5000/order-service-ecommerce-boot
    newTag: latest
  - name: selimhorri/payment-service-ecommerce-boot
    newName: localhost:5000/payment-service-ecommerce-boot
    newTag: latest
  - name: selimhorri/shipping-service-ecommerce-boot
    newName: localhost:5000/shipping-service-ecommerce-boot
    newTag: latest

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: SPRING_PROFILES_ACTIVE
            value: "stage"
          - name: SPRING_ZIPKIN_BASE_URL
            value: "http://zipkin-service:9411/"
          - name: SPRING_CONFIG_IMPORT
            value: "optional:configserver:http://cloud-config:9296"
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent

